# Generated by Django 3.1.5 on 2021-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210115_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
