# Generated by Django 3.1.5 on 2021-01-15 19:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20210115_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reservada', models.BooleanField(default=False)),
                ('en_uso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('codigo', models.CharField(max_length=10)),
                ('cantidad_covers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Covers')),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.zona')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.zona'),
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_inicial', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.zona')),
            ],
        ),
    ]
