# Generated by Django 3.1.5 on 2021-01-15 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_evento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
