# Generated by Django 3.1.5 on 2021-01-15 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20210115_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_covers',
        ),
        migrations.AddField(
            model_name='mesa',
            name='cant_covers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Covers'),
        ),
    ]
