# Generated by Django 3.1.5 on 2021-01-15 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20210115_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ReservaLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='articulos',
            field=models.ManyToManyField(to='reservas.ReservaLinea', verbose_name='Articulos de la mesa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='articulos',
            field=models.ManyToManyField(to='reservas.ReservaLinea', verbose_name='Articulos de la mesa'),
        ),
    ]
