# Generated by Django 3.1.5 on 2021-01-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20210115_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='articulos',
            field=models.ManyToManyField(blank=True, to='reservas.ReservaLinea', verbose_name='Articulos de la mesa'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='articulos',
            field=models.ManyToManyField(blank=True, to='reservas.ReservaLinea', verbose_name='Articulos de la mesa'),
        ),
    ]
