# Generated by Django 3.1.5 on 2021-01-18 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_remove_reserva_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
