# Generated by Django 3.1.5 on 2021-01-21 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_auto_20210118_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cant_covers_adicional',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Covers Adicionales'),
        ),
    ]
