# Generated by Django 3.1.5 on 2021-01-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_cant_covers_adicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('sinreclamar', 'Sin Reclamado'), ('reclamado', 'Reclamado')], default='sinreclamar', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.tiporeserva', verbose_name='Tipo de reserva'),
        ),
    ]
