# Generated by Django 3.1.5 on 2021-02-10 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_auto_20210125_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=50)),
                ('locacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_evento',
        ),
    ]
