# Generated by Django 3.1.5 on 2021-02-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_auto_20210210_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.evento', verbose_name='Evento'),
        ),
    ]
